elementalui/elemental

site/src/pages/Forms.js

Fix for #13. :sparkle: 
Also fix for a couple of warnings:
```
Warning: Failed propType: Required prop `onChange` was not specified in `FormSelect`. Check the render method of `VIEW_Forms`.
```
and
```
Warning: Failed propType: Invalid prop `value` of type `object` supplied to `FormSelect`, expected `string`. Check the render method of `VIEW_Forms`.
```
And I was wrong about `controlOptions` => `options` in #12. Also fixing it. :sparkle:

Fix FormSelect warnings on Forms page.

---

lib/components/Alert.js
lib/components/Button.js
lib/components/Dropdown.js
lib/components/FormIconField.js
lib/components/FormLabel.js
lib/components/FormRow.js
lib/components/FormSelect.js
lib/components/Modal.js
lib/components/RadioGroup.js
lib/components/Tooltip.js
src/components/Button.js
src/components/Dropdown.js
src/components/FormIconField.js
src/components/FormLabel.js
src/components/FormSelect.js
src/components/Modal.js
src/components/RadioGroup.js
src/components/Tooltip.js

When I was fixing #13, I've found out that `option` always is DOM event object instead of `e.target.value` here [Forms.js#L70](https://github.com/AlexKVal/elemental/blob/eb418e03361d04b14831d765dbacc85074bd7b3b/site/src/pages/Forms.js#L70)
It is because of `onChange` from `{...props}` overrides `onChange={this.handleChange}` here [FormSelect.js#L103](https://github.com/AlexKVal/elemental/blob/9a6a8c4d4932b6a1ebde199c551c4cbf1463bc67/src/components/FormSelect.js#L103)
if I place `{...props}` *before* `onChange=`, like this
```js
<select className="FormInput" id={forAndID} {...props} onChange={this.handleChange} onBlur={this.handleBlur}>
```
then the right `this.handleChange` is fired and everything works fine.
The cause it that  `blacklist` doesn't filter out `onChange` here …

Fix bug with blacklist package usage.

---

.eslintrc
package.json
site/src/pages/Forms.js
site/src/pages/Modal.js
src/components/FileDragAndDrop.js
src/components/FileUpload.js

The new "object-curly-spacing" eslint rule https://github.com/eslint/eslint/pull/2515/files has been finally implemented.
It seems it is long awaited https://github.com/eslint/eslint/issues/2225#issue-66089460.
But it doesn't work for JSX. 
E.g. there is no warning here [FileDragAndDrop.js#L76](https://github.com/elementalui/elemental/blob/3a46a41965be0ac9d0aa9a775597cd8d20974298/src/components/FileDragAndDrop.js#L76)
And it won't be implemented in `eslint` according to https://github.com/eslint/eslint/issues/2225#issuecomment-89345117
> It should apply to restructured objects but not JSX.
Maybe [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) eventually will implement it. (if someone creates feature requests)

Just proposal. Impose "object-curly-spacing" eslint rule.

---

src/components/Dropdown.js

Eliminates 
```
Warning: Don't set .props.onClick of the React component <h3 />.
...
Warning: Don't set .props.className of the React component <h3 />.
```
on the http://elemental-ui.com/buttons page.

Use React.cloneElement() for child elements.

---

less/components/FormInput.less

 Select input styling is broken in Firefox #22

---

site/src/pages/Modal.js
src/components/Modal.js

1. I've used only pageYOffset since there is no support for <IE9
2. Added more random text to Modal page so we can see fix working
3. Added `props.top` so it is possible to override automatic placement. Could be also set to skip `window.pageYOffset` evaluation in case `window` object is not available at all

Modal box is opened out of screen #24

---

less/components/Modal.less
package.json
src/components/Modal.js

It looks sluggish on gif, but in fact is pretty smooth.
I added this to the demo modal box to test modal that is higher then screen:
```js
<ModalFooter>
{submitButton}
<Button onClick={this.toggleModal} type="link-cancel" disabled={this.state.formProcessing}>Cancel</Button>
</ModalFooter>
<div style={{background: 'linear-gradient(to bottom, rgba(201,222,150,1) 0%,rgba(138,182,107,1) 44%,rgba(57,130,53,1) 100%)', height: window.innerHeight}} />
```

Modal should follow scroll (fixes #26)

---

site/src/pages/Forms.js
src/components/PasswordInputGroup.js

It would be nice to set the password validator by passing it via `props` to fit various application requirements.
Moreover, I noticed that the feature can be utilized to build confirm password field, where an example is given in the `sites/Forms.js`.

enable custom password validator in PasswordInputGroup

---

src/components/Col.js

Often you want a `<Col>` merely for layout purposes / with no content. Seems to currently work fine when using `<Col/>` except there is a prop warning. One can do `<Col><span/></Col>` and everything still works and no error. This just gets rid of the children requirement.

Allow `Col` to have no children

---

src/components/FileUpload.js

file input onchange isn't triggered when they select a file with the same name

fix a fileUpload bug

---

site/src/pages/Buttons.js
src/components/Button.js

This is useful for integrating React Router's `<Link>` elements (http://rackt.github.io/react-router/#Link).
Not sure this is the best way to go about it (I'm a JS n00b), feel free to give me feedback!
Why I needed to do this:
* If I wrap a `<Button>` in a React Router `<Link>`, it is rendered as `<a><button>` instead of just a `<a>`. This screws up some styling and semantics.
* I can't get the raw `href` value from React Router to pass to `<Button>` before the component has rendered (AFAIK).
* I can imagine a world where someone would want to create their own `<CustomLink>` or whatever and have that passed through instead of using a raw `<a>`.

Add `component` prop to `Button`, which is rendered instead of creating a `<a>` or `<button>`

---

.npmignore
bower.json
package.json
scripts/bower.sh

Script for automatic publishing to Bower.
For now OSX/Linux only
To test, I checked out `v0.5.1` tag, applied patch with these changes and run script.

Bower support, fixes #39

---

package.json
site/src/pages/Modal.js
src/components/Modal.js
src/components/ModalHeader.js

This PR fixes a couple of accessibility issues in the `Modal` component, by using the [`ally.js`](https://github.com/medialize/ally.js) package.
* Make sure no element outside of the modal can be focused (by any means, including keyboard and mouse)
* Focus the first keyboard focusable (tabbable) element in the modal upon opening the modal, or focus the modal itself, if it doesn't contain any focusable elements
* Focus the element that had focus before the modal was shown upon closing the modal
* Make sure no element outside of the modal is visible to screen readers (analog to how we obfuscate the content visually by way of the backdrop)
* Make sure to transfer focus to the modal only when the modal is visible, to avoid the document from being scrolled by the browser

Accessibility fixes for the `Modal` component

---

gulpfile.js

Checked with this file:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Title</title>
<link rel="stylesheet" href="./dist/elemental.css">
</head>
<body>
Hello!
<script src="https://npmcdn.com/react@0.14.3/dist/react.min.js"></script>
<script src="https://npmcdn.com/react-dom@0.14.3/dist/react-dom.min.js"></script>
<script src="https://npmcdn.com/classnames@2.2.1"></script>
<script src="https://npmcdn.com/blacklist@1.1.2"></script>
<script src="./dist/elemental.js"></script>
</body>
</html>
```
Does not throw an exception. Though I need to check a bit more if it actually works fine.
The only problem left - `blacklist`. It does not have UMD wrapper. I'll PR there.

[WIP] Classnames exports window.classNames and not window.classnames, fixes #85

---

.gitignore
.npmignore
package.json
test/components/Pagination-test.js
test/index.js

A #58 spinoff
Works perfectly under Windows.
Tests are super basic with literally zero logic overhead. TAP is common API, supported by pretty much anything. Can add `tap-xunit`, for example, to export CI-friendly XML, and so on.
And it is lightning fast (the only short warm-up overhead added by babel). With node v4 we can step back to `require` and remove babel-node, since it supports most of ES6 syntax.
Coverage report is present too:
Ping @MunGell @JedWatson @zackify

Add testing setup with Tape and Isparta

---

src/constants.js

When using fractions in the Col component it is intuitive to use '1' to mean '100%'.

use '1' for '100%' in Col constants when using fractions

---

site/src/pages/Modal.js

The property affecting the size (or, rather, the width) of Modal is `width`, not `size`.

Fixed incorrect documentation demonstrating Modal sizes

---

src/components/Table.js

Fixes #133
This PR moves `className` so that it takes precedence over the `props` spread.  We could use blacklist here instead, but other components seem to solve the same problem in this way.

Keep Table class when specifying className

---

src/components/FileDragAndDrop.js

different browsers may use different default types for the <button> element,
in my chrome Version 48.0.2564.116, the default type is 'submit', so it will trigger submit event,

should always specify the type attribute

---

src/components/Pagination.js

see example at http://elemental-ui.com/misc, change the total nr of records to 200, click the right ellipsis, then click the left ellipsis, `currentPage` becomes undefined.

fix for page_start pagination button

---

src/components/FormInput.js

This gets rid of the warning in React 15.2+
Note that `autofocus` needs stripping too, but if you implement #165 this is not necessary.

Strip non-<input> props

---

site/src/pages/Forms.js
src/components/FormSelect.js

This fix adds `disabled` prop to options of `<FormSelect>` component, which is mentioned in #177 .
I didn't include updates for the documentation. Because I feel that the example code of `<FormSelect>` is not enough to me. It doesn't show a shape of `options` prop.
```
<FormSelect options={[...]} firstOption="Select" onChange={this.handleSelect} />
```
How about following example code? It's somewhat ugly but I have no idea to show this.
Please let me know your comment 😃 
```
const controlOptions = [
{ label: 'Caramel',    value: 'caramel' },
{ label: 'Chocolate',  value: 'chocolate' },
{ label: 'Strawberry', value: 'strawberry' },
{ label: 'Vanilla',    value: 'vanilla', disabled: true }
];
// ...
<FormSelect options={controlOptions} firstOption="Select" onChange={this.handleSelect} /> …
```

Add 'disabled' prop to options for FormSelect

---

less/base/forms.less

I think this makes sense because Checkbox and Radio are already given `line-height: @component-height`, which is by default `33px`. The margin makes them too faraway from each other.
Before:
After:
Also, it will fix the issue that Checkbox labels in basic forms and horizontal forms have different height because horizontal form applies `display: table` to `.FormField`.

Remove margin-bottom of Checkbox and Radio for large screens

---

site/src/pages/Misc.js
src/components/Pagination.js

This PR resolves #182.
In most cases, `singular` and `plural` props are enough for customization of pagination's labels.
Some users (including me) have a problem on i18n.
I don't prefer the explosion of props, I choose a format function. This is not friendly for beginners, but a topic of i18n is a headache for advanced users.
Any feedbacks are welcome 😃

Add new prop "label" to customize pagination's labels
